const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "MAKAMESCO-MD<=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid05VNERqYmlkMFlNZjJrT0tjaklXWnIrNUxCaWdFSitVZml0c0FvVmVWTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOVBwRVYvU1RtUTJKTTd0endCVHVNZFJvRzNFTUdCMlRXa1lWMktwWjJ3WT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI2SHdNUFZQbWtIZE1ZMWVqRTI3QVFWSDJiRkdPdUxUZVhLTFhjM01OK25FPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2RW9KcFB3UlRSSjQrVG1TVXRsODRpTCtCdHI1TFVPYVZFUFU5b2tjVVZNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNFNFM2NGpnNkNveGhoZXVuV211SWlhc0QvSUk3UlIzRVA2WXRlSWYra1k9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjVCVHA0TkZBYjNLS0VCTG5Qck4vbk9vWW5GR09pZlNJQjRUSU9XNWU4Ujg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0IreXNpSGN6Q3NKcGlRYk5HeUQ3VlpYaXZWV0MzNlkrbUJJTkpyRzVWMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVGYxZi9hNXhuazBuSzNSblJmVWt1MG9UOFVBN0NHN1FzRmtHMEJacmlHRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNSOXp0WWIzUmx3RVhoN20xeVB5L2NKb0xQWWlmV1FGWUZ3ZUtqdVBjRGxqc1pMMFl6QVNRMmFROUNKMDdkZTNQU1pkQ1VlUkVqK3dKL2NVN3FPVGd3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTgsImFkdlNlY3JldEtleSI6ImczLzZjSzhVRUczTTJmN0ZJWjlkdlNDaXhiYXc3MzR6SHg4SjJQVElrSk09IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU1NjI5MzA4MTU0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjBDODc4N0MwM0UwQUU2OUE0Njg3REI2N0I5OTA3OTY2In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTI1MDM0MDN9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NTYyOTMwODE1NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJFRUUyMEIwNkY2NDEyQ0RBNjQ5M0MxQTgwQkI0NkEyQSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUyNTAzNDAzfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJwM0NlRFNCcFR1R3I2SmhDQ25Ec29BIiwicGhvbmVJZCI6IjA3NjM4N2QyLWM3ODQtNDkxOS05ZTAzLTE5MGMzNDA0YmMyZSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIyK0VYdm03Z3Rpc3RReGJQSUtJSjdYcnl4ZWs9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZlBRbnRqV2MwZnhCSkcvL1crd0p5Uk94NElZPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkZSRURFWlJBIiwibWUiOnsiaWQiOiIyNTU2MjkzMDgxNTQ6MzdAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxMjYwMzY0NTI4OTY4NjQ6MzdAbGlkIiwibmFtZSI6IkFsbHkgU2NvdHQgMyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTG5lOHJzQ0VOaW8xTU1HR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoicWZNNzc4R3dTUE9VbEVadmd6VkVUNFpLd1RUVFVEa0lSaW1aRnNVZ0lqOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiM3BlMng0Y3JiRGpncmIxUHVYcGgyQnhwNExURjVNT1l2Sk5lTDlEd0s5cFRTbE5jRHRHUGNCU25CS3FIN01iYlkvcXZWM2grVFRYMVRSNnZJdGlTQVE9PSIsImRldmljZVNpZ25hdHVyZSI6IlJBbVUwbmk3M1hCOFd1ZVFvd3R0Z1NyclZaajhLdVV6WUZUcEcwVEZOeHRMYzJQOW9jeGsvV0tPQ2RnOVRBd3NJTWhBb2tSRlpSR25adS9lYStNdWp3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU1NjI5MzA4MTU0OjM3QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmFuek8rL0JzRWp6bEpSR2I0TTFSRStHU3NFMDAxQTVDRVlwbVJiRklDSS8ifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlEUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1MjUwMzM5OCwibGFzdFByb3BIYXNoIjoiMkc0QW11IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFMUjMifQ==",
  PREFIX: process.env.PREFIX || ".",
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === "true" : true,
  AUTO_LIKE: process.env.AUTO_LIKE !== undefined ? process.env.AUTO_LIKE === "true" : true,
  AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY !== undefined ? process.env.AUTO_STATUS_REPLY === "true" : false,
  STATUS_READ_MSG: process.env.STATUS_READ_MSG || "",
  ANTI_DELETE: process.env.ANTI_DELETE !== undefined ? process.env.ANTI_DELETE === "true" : false,
  ANTI_DELETE_PATH: process.env.ANTI_DELETE_PATH || "inbox",
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === "true" : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === "true" : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === "true" : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === "true" : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === "true" : true,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === "true" : false,
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === "true" : false,
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === "true" : false,
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === "true" : false,
  MODE: process.env.MODE || "public",
  BOT_NAME: process.env.BOT_NAME || "Makamesco-MD",
  MENU_IMAGE: process.env.MENU_IMAGE || "https://files.catbox.moe/sigghy.jpg'/",
  DESCRIPTION: process.env.DESCRIPTION || "Savage WhatsApp Bot by Toxic-Master",
  OWNER_NAME: process.env.OWNER_NAME || "Marcas",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "254769995625",
  GITHUB_TOKEN: process.env.GITHUB_TOKEN || "",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === "true" : false,
};

module.exports = config;
